_commit: 7f6d32f1cca85e419664ac8a06f31b78ad67d4b0
_src_path: https://github.com/ORINOCO-Lite/orinoco-lite-template.git
project_slug: psychoinformatics-comparison
project_name: Psychoinformatics comparison
site_description: Retained-capture comparison of the Psychoinformatics website.
site_base_url: https://orinoco-lite.github.io/psychoinformatics-downstream/
pr_previews: none
include_site_specific: false
package_repository: https://github.com/ORINOCO-Lite/orinoco-lite-dev.git
package_revision: ae4601dbc519e89af98879366dfec67245a59bfd
